#!/usr/bin/zsh

COMMAND_NAME="offline"
STORED_COMMANDS="${HOME}/.${COMMAND_NAME}.commands"
TEMP_FILE="/tmp/${COMMAND_NAME}.tmp"

function _offline-help() {
cat << _EOH_
USAGE: offline <command> [arguments]

COMMAND:

    -l | list            List all the offline commands
    -x | execute         Execute all offline comands
    -h | help            Show this help message

_EOH_
}

function _offline-list() {
    [ -e "$STORED_COMMANDS" ] && cat "$STORED_COMMANDS"
}

# Run all the commands in the given file
function _offline-execute() {
    # Exit if there are no commands to execute
    [ -e "$STORED_COMMANDS" ] || exit 0

    # Make a copy in the temp folder
    cp "$STORED_COMMANDS" "$TEMP_FILE" && rm -f "$STORED_COMMANDS" && touch "$STORED_COMMANDS"

    # Now run each command one by one
    while read line; do
        eval "$line" || echo "$line" >> "$STORED_COMMANDS"
    done < "$TEMP_FILE"

    # Delete the tmp file
    rm -f "$TEMP_FILE"
}

# Append the offline command to a log
function _offline-store() {
    # Check if the file exists or not
    [ -e "$STORED_COMMANDS" ] || touch "$STORED_COMMANDS"

    # Append the command to the file
    echo "cd $PWD && $*" >> "$STORED_COMMANDS"
}

# Parse the arguments
case "$1" in
    help|-h|--help)                         _offline-help;;
    list|-l|--list|--ls)                    _offline-list;;
    execute|-x|--execute)                   _offline-execute;;
    *)                                      _offline-store "$*";;
esac
