#!/usr/bin/env bash

# Browse Ramda documentation in Terminal
# Requires jq and a tool such as fzf for interactive filtering

# Get the json data
LATEST="https://raw.githubusercontent.com/raine/ramda-json-docs/gh-pages/latest.json"
DOCS_URL="http://ramdajs.com/docs/"
json=$(curl -s $LATEST)

# Get function data
functions=$(echo "$json" | jq -r '.[] | if .sig and (.sig | length > 0) then .name + " :: " + .sig else .name end')

# Now let the user select the function he wants
fn=$(echo "$functions" | fzf --reverse) || exit 0

# Get the documentation for the selected function
fn_name=$(echo "$fn" | awk '{print $1}')
desc=$(echo "$json" | jq -r ".[] | select(.name == \"$fn_name\") | .description" | fmt)
docs_url="$DOCS_URL#$fn_name"

echo "$fn"
echo
echo "$desc"
echo
echo "$docs_url"

# Open URL in browser
# open $docs_url
# xdg-open $docs_url # linux
