#!/bin/sh

TYPE=$1
OUTFILE=$2

# Row output
echo "QUERY\tMAX\tMIN\tAVG\tSTD"

# Compute the maximum
MAX=$(awk -v TYPE="$TYPE" '$1==TYPE {print $2}' "$OUTFILE" | sort -nr | head -1)
MIN=$(awk -v TYPE="$TYPE" '$1==TYPE {print $2}' "$OUTFILE" | sort -n | head -1)
AVG=$(awk -v TYPE="$TYPE" '$1==TYPE {print $2}' "$OUTFILE" | awk 'BEGIN {count=0} {count+=$0} END {print count/100}')
STD=$(awk -v TYPE="$TYPE" '$1==TYPE {print $2}' "$OUTFILE" | awk -v AVG="$AVG" 'BEGIN {sum=0} {sum=($0-AVG)^2} END {print sqrt(sum/100)}')

# Row output
echo "$TYPE\t$MAX\t$MIN\t$AVG\t$STD"
